# 基本配置
server:
  port: 8080


spring:
  data:
    mongodb:
      uri: mongodb://118.25.6.146:27017/comment

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40c{1.} [%X{user}] : %m%n%xwEx"

# 简书配置
jianshu:
  user-id: 7b7ec6f2db21